[general]
# General application settings
log_level = "info"
output_format = "json"
enable_gpu = false
thread_count = 0  # 0 = auto-detect

[processing]
# Processing pipeline settings
enable_oscillatory_decomposition = true
enable_ambiguous_compression = true
enable_linguistic_transformation = true
enable_sequence_encoding = true
enable_s_entropy_navigation = true

[sequence_encoding]
# Directional sequence encoding parameters
activation_threshold = 0.7    # A = Elevated/Activation
steady_threshold = 0.3        # R = Steady/Maintenance  
recovery_threshold = -0.3     # D = Decreased/Recovery
stress_threshold = 0.9        # L = Stress/Transition

[context]
# Contextual analysis parameters
enable_circadian_weighting = true
enable_activity_correlation = true
enable_environmental_factors = true
enable_historical_patterns = true

[validation]
# Validation and quality control
enable_consistency_checks = true
anomaly_detection_threshold = 3.0
confidence_threshold = 0.5
require_minimum_context = true
